apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: election-production

commonLabels:
  environment: production

resources:
  - ../../base

replicas:
  - name: election-app
    count: 3

images:
  - name: ghcr.io/owner/election-app
    newTag: v1.0.0

configMapGenerator:
  - name: election-app-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=production

patchesStrategicMerge:
  - ingress-patch.yml
  - resources-patch.yml
